const chistes = [
  "¿Qué hace una abeja en el gimnasio? ¡Zum-ba!",
  "¿Cuál es el café más peligroso del mundo? El ex-preso.",
  "¿Qué hace un pez? Nada.",
  "¿Qué le dice un semáforo a otro? No me mires que me estoy cambiando.",
  "¿De dónde vienen los hámster? De Hamsterdam.",
  "¿Cómo se dice pañuelo en japonés? Saka-moko.",
  "¿Cuál es el animal más antiguo? La cebra, porque es en blanco y negro.",
  "¿Qué le dijo un techo a otro techo? Techo de menos.",
  "¿Cómo haces para que un pan hable? Lo pones en agua toda la noche y al día siguiente ya está blando.",
  "¿Por qué los esqueletos no pelean entre ellos? Porque no tienen agallas.",
  "—Papá, ¿qué se siente al tener un hijo tan guapo? —No lo sé, pregunta a tu abuelo.",
  "—Maestra, ¿me castigaría usted por algo que yo no hice? —¡Por supuesto que no! —¡Qué alivio!, porque no hice la tarea de hoy.",
  "¿Por qué la ballena no come? Porque ba-llena.",
  "—¿Qué le dice una iguana a su hermana gemela? —¡Iguanita!",
  "—¿Tienes WiFi? —Sí. —¿Cuál es la clave? —Tener dinero y pagarlo.",
  "Una pareja de ancianos está en la cama y ella le dice al marido: «Pareces un teléfono móvil». Él responde: «¿Por qué? ¿Vibro mucho?» «Porque cuando entras en el túnel te quedas sin cobertura».",
  "¿Qué pasa si tiras un pato al agua? —Nada.",
  "¿Cuál es el apellido de Adán y Eva? —Pérez, porque el Señor les dijo “si comes del fruto, Pérez serás”.",
  "—¿Cómo se llama el hermano vegetariano de Bruce Lee? —Broco Lee.",
  "—¿Cuál es el colegio perfecto? —Cerrado.",
  "Entra un hombre con mucho pelo en una consulta del médico y pregunta: «Doctor, ¿qué padezco?» —«Padece usted un ocito».",
  "—¿Cómo se queda un mago después de comer? —Magordito.",
  "¿Cómo se llama un hotel muy desagradable? —Una posadilla.",
  "—¿Qué pesa más, un pájaro de tres kilos o un gato de tres kilos? —El pájaro, porque pesa tres kilos y pico.",
  "—¿Cuál es el vino más amargo? —Vino mi suegra.",
  "—¿Qué diferencia hay entre una suegra y un terrorista? —Que con el terrorista se puede negociar.",
  "—¿Qué le dijo el número 1 al número 10? —Para ser como yo, tienes que ser sincero (sin cero).",
  "¿Por qué hablas con tus zapatillas? —Es que en la caja dice Converse.",
  "—¿Qué dijo una cereza cuando se vio al espejo? —¿Cereza yo?",
  "—¿Cuál es el animal más rico? —El borrego, porque tiene lana.",
  "—¿Qué le dijo un jaguar inglés a otro? —Jaguar you!",
  "—¿Qué hace el pez en la mañana? —Nada.",
  "—¿Cuántas estrellas hay en el cielo? —Cincuenta (sin cuenta).",
  "—¿Qué le dijo un jaguar…? —Jaguar you!",
  "—Mamá, mamá, en el colegio me dicen vago. —¿Y tú qué haces? —¡Nada!",
  "—Mamí, en el colegio me va como en el Polo Norte. —¿Ah sí? ¿Cómo es eso? —Todo estuvo bajo cero.",
  "—Mamá, mamá, ¡me picó una serpiente! —¿Cobra? —No, gratis!",
  "¿Cuál es el animal que camina con una pata? —El pato.",
  "—¿Qué le dijo un hombre a otro que estaba llorando? —No llores, que el lobo te oye y se ríe.",
  "¿Qué haces si un pájaro de tres kilos y un gato de tres kilos se suben a tu cabeza? —Tienes un gorro muy pesado.",
  "—¿En qué son diferentes una bomba, la luna y la familia? —La bomba estalla, la luna está allá, ¡y la familia está muy bien, y la tuya?",
  "—¿Qué le dijo un soldado en la frontera sin armas? —Sabeti sabeti sabeti!",
  "—¿Cómo se llama el hermano del espantapájaros que era músico? —El pajarófono.",
  "—¿Por qué los peces son los animales más valientes? —Porque tienen agallas.",
  "—¿Por qué los pájaros no usan Facebook? —Porque ya tienen Twitter.",
  "—¿Qué hace un gato después de chocar su carro? —¡Miauto!",
  "—¿Cuál es el café más explosivo? —El ex-preso (espresso).",
  "—¿Qué le dice un reloj a otro reloj? —¡Hora de cambiar!",
  "—¿Por qué los esqueletos no van al gimnasio? —Porque no tienen cuerpo.",
  "—¿Qué le dice un semáforo a otro semáforo cuando están de fiesta? —¡Cambio, cambio!",
  "—¿Cómo se llama un pez que no nada bien? —Un pecun… no, mejor que no lo diga.",
  "—¿Qué le dijo una campana a otra campana? —¿Ding-dong?",
  "—¿Por qué el libro de matemáticas estaba triste? —Porque tenía muchos problemas.",
  "—¿Qué hace un plátano en el hospital? —¡Ban-dido!",
  "—¿Cuál es el héroe más perezoso? —Snoo-man.",
  "—¿Cuál es la fruta más divertida? —La naranja, porque siempre está de buen “humor-aje”.",
  "—¿Qué hace una computadora cuando tiene frío? —Pone Windows… y se resfría.",
  "—¿Cómo se despiden los químicos? —Ácido un placer.",
  "—¿Por qué la luna fue al gimnasio? —Para ponerse en forma-ción.",
  "—¿Qué hace un árbol en la playa? —Sombra.",
  "—¿Por qué la escoba no se cansa? —Porque siempre está barriendo.",
  "—¿Qué le dijo una impresora a otra? —¿Esa hoja es tuya o es una impresión mía?",
  "—¿Cómo se llama el pez que ama la música? —El tuna-fish.",
  "—¿Por qué la sandía sabía tanto? —Porque tenía muchas pepitas.",
  "—¿Qué hace un caracol en un gimnasio? —¡Snail-fit!",
  "—¿Por qué los esqueletos no van al cine? —Porque no tienen “cuerpo” para la butaca.",
  "—¿Qué hace un globo en clase? —¡Silu-eta!",
  "—¿Cómo se llama el boomerang que no vuelve? —Un palo.",
  "—¿Por qué la ventana fue al doctor? —Porque se sentía “cristal-izada”.",
  "—¿Qué hace un reloj roto? —Sigue siendo la hora… dos veces al día.",
  "—¿Qué le dijo una hamburguesa a otra? —Nos vemos en el pan.",
  "—¿Cuál es el colmo de un jardinero? —Que siempre lo dejen plantado.",
  "—¿Por qué la galleta fue al médico? —Porque se sentía migaja.",
  "—¿Cuál es el colmo de un matemático? —Tener problemas en casa.",
  "—¿Qué le dijo un plátano a una gelatina? —¡No tiemblo, tiemblo yo!",
  "—¿Por qué los esqueletos no cuentan chistes? —Porque ya no tienen “hueso” para reír.",
  "—¿Qué hace una abeja en el banco? —Pide “miel-ros”."
];

document.getElementById("btn-chiste").addEventListener("click", () => {
    const random = Math.floor(Math.random() * chistes.length);
    document.getElementById("chiste").textContent = chistes[random];
});